In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9199, 8529, 4993, 1596],
 [9199, 8529, 4993, 2276],
 [9199, 258, 4993, 9646],
 [5811, 5895, 5794, 3392, 1713],
 [5811, 5895, 5794, 3392, 7456],
 [48, 9199, 4801, 4993, 6736],
 [8191, 5201, 739, 3392]]

In [7]:
##Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length =8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [10]:
print(embedded_docs)

[[   0    0    0    0 9199 8529 4993 1596]
 [   0    0    0    0 9199 8529 4993 2276]
 [   0    0    0    0 9199  258 4993 9646]
 [   0    0    0 5811 5895 5794 3392 1713]
 [   0    0    0 5811 5895 5794 3392 7456]
 [   0    0    0   48 9199 4801 4993 6736]
 [   0    0    0    0 8191 5201  739 3392]]


In [11]:
#Feature representation
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))#This gives embedding layer
model.compile('adam','mse')


In [15]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs) # Since our outputshape is 8x10, it gave the prediction in 8x10 array

1/1 [==============================] - 1s 713ms/step


array([[[-0.01254117, -0.01646322, -0.01290501,  0.0346261 ,
         -0.02174709,  0.02682247, -0.04882323, -0.03691223,
         -0.02325277,  0.04501173],
        [-0.01254117, -0.01646322, -0.01290501,  0.0346261 ,
         -0.02174709,  0.02682247, -0.04882323, -0.03691223,
         -0.02325277,  0.04501173],
        [-0.01254117, -0.01646322, -0.01290501,  0.0346261 ,
         -0.02174709,  0.02682247, -0.04882323, -0.03691223,
         -0.02325277,  0.04501173],
        [-0.01254117, -0.01646322, -0.01290501,  0.0346261 ,
         -0.02174709,  0.02682247, -0.04882323, -0.03691223,
         -0.02325277,  0.04501173],
        [ 0.01047353,  0.00555897, -0.02772356,  0.04575317,
          0.00990902,  0.01811877, -0.04366532, -0.00172504,
         -0.0226947 ,  0.04773797],
        [ 0.02430413, -0.00089125,  0.03071202, -0.00987459,
          0.04204397,  0.03456799,  0.04201928, -0.00673924,
          0.03065064,  0.00631828],
        [ 0.03522882, -0.01571082, -0.00198706,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 9199, 8529, 4993, 1596])

In [19]:
model.predict(embedded_docs[0]) #The model’s output/probability for that input

1/1 [==============================] - 0s 133ms/step


array([[-0.01254117, -0.01646322, -0.01290501,  0.0346261 , -0.02174709,
         0.02682247, -0.04882323, -0.03691223, -0.02325277,  0.04501173],
       [-0.01254117, -0.01646322, -0.01290501,  0.0346261 , -0.02174709,
         0.02682247, -0.04882323, -0.03691223, -0.02325277,  0.04501173],
       [-0.01254117, -0.01646322, -0.01290501,  0.0346261 , -0.02174709,
         0.02682247, -0.04882323, -0.03691223, -0.02325277,  0.04501173],
       [-0.01254117, -0.01646322, -0.01290501,  0.0346261 , -0.02174709,
         0.02682247, -0.04882323, -0.03691223, -0.02325277,  0.04501173],
       [ 0.01047353,  0.00555897, -0.02772356,  0.04575317,  0.00990902,
         0.01811877, -0.04366532, -0.00172504, -0.0226947 ,  0.04773797],
       [ 0.02430413, -0.00089125,  0.03071202, -0.00987459,  0.04204397,
         0.03456799,  0.04201928, -0.00673924,  0.03065064,  0.00631828],
       [ 0.03522882, -0.01571082, -0.00198706,  0.01941048,  0.01290942,
         0.01620375,  0.03591954,  0.0089565 